# Generated by Django 5.2.1 on 2025-05-31 18:40

import barber.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AlterField(
            model_name='barber',
            name='available_hours',
            field=models.JSONField(blank=True, default=barber.models.Barber.default_available_hours, null=True),
        ),
    ]
