# Generated by Django 5.2.1 on 2025-05-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0002_remove_service_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('usuario', 'usuario'), ('barbeiro', 'Barbeiro'), ('admin', 'Administrador')], default='cliente', max_length=20),
        ),
    ]
