# Generated by Django 5.2.1 on 2025-05-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_remove_appointment_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_cell',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
